'use client'

import { useMemo, useState } from 'react'

const teaser = [
  ['Presence','When you enter a new professional environment, what do you naturally do first?',['Observe and understand the room','Introduce myself and build rapport','Look for where I can contribute','Wait until I understand what is expected']],
  ['Relationships','When collaboration becomes difficult, what is your first instinct?',['Create space for an honest conversation','Focus on the shared objective','Find the source of the tension','Take responsibility for moving things forward']],
  ['Intelligence','When a problem is unfamiliar, what do you naturally do?',['Look for patterns','Ask people with relevant experience','Break the problem into smaller parts','Experiment and learn quickly']],
  ['Mastery','What best describes how you approach work you care about?',['I establish a clear standard','I keep improving the process','I stay with it until it is done properly','I learn from what did not work']],
  ['Enterprise','When you notice an unmet need, what are you most likely to do?',['Think about who could benefit','Imagine a better way to solve it','Look for a practical first step','Consider whether it could become something bigger']],
  ['Presence','What helps you communicate your value most effectively?',['Clarity','Credibility','Confidence','Evidence of what I have delivered']],
  ['Relationships','What makes a professional relationship meaningful to you?',['Trust','Mutual growth','Reliability','Shared purpose']],
  ['Intelligence','When two credible people disagree, what do you look for?',['The strongest evidence','The assumptions underneath each view','The consequences of each option','A way to test both ideas']],
  ['Mastery','When you make a mistake, what happens next?',['I understand what caused it','I correct it quickly','I change the process so it is less likely to repeat','I ask for feedback']],
  ['Enterprise','What does creating value mean to you?',['Solving a real problem','Making something more useful','Creating measurable outcomes','Opening a new possibility']],
  ['Presence','Which statement feels closest to how you want to be remembered professionally?',['Clear and composed','Trusted and credible','Bold and distinctive','Consistently valuable']],
  ['Relationships','When someone needs your help professionally, what do you usually do?',['Listen first','Offer a practical solution','Connect them to someone useful','Help them work through it themselves']],
  ['Intelligence','How do you usually make an important decision?',['Gather the relevant facts','Compare possible consequences','Combine evidence with experience','Test the decision against the bigger picture']],
  ['Mastery','What keeps you improving when nobody is watching?',['Personal standards','Curiosity','Pride in the work','The desire to become more capable']],
  ['Enterprise','Which opportunity would most excite you?',['Building something useful','Solving a difficult commercial problem','Creating a new professional pathway','Turning an idea into a sustainable system']],
]

const full = [
  ['Presence','How clearly can you explain what you do and the value you create?',['Very clearly','Clearly in most situations','It depends on the audience','I am still finding the right language']],
  ['Presence','When you need to influence a room, what do you rely on most?',['Preparation','Clarity of thought','Relationship and trust','Confidence and conviction']],
  ['Presence','How intentionally do you manage your professional reputation?',['Very intentionally','Mostly intentionally','Only when necessary','I have not thought much about it']],
  ['Relationships','How do you build trust with people who work differently from you?',['Listen and adapt','Establish expectations','Find common ground','Give trust first']],
  ['Relationships','When feedback is uncomfortable, what do you tend to do?',['Listen carefully','Ask questions','Reflect privately','Act immediately']],
  ['Relationships','How do you maintain professional relationships over time?',['Regular contact','Useful collaboration','Offering support','Shared projects and goals']],
  ['Intelligence','How comfortable are you making decisions with incomplete information?',['Very comfortable','Comfortable with clear assumptions','I prefer more evidence','I usually seek advice first']],
  ['Intelligence','How do you distinguish an important problem from a noisy one?',['Look at impact','Look at root cause','Look at strategic relevance','Look at urgency and consequences']],
  ['Intelligence','When evidence changes your view, what happens?',['I change direction quickly','I test the new evidence','I discuss it with others','I need time to integrate it']],
  ['Mastery','How consistently do you turn good intentions into completed work?',['Very consistently','Usually','It varies with the project','I am actively improving this']],
  ['Mastery','What do you do when your current skill is not enough for the task?',['Learn immediately','Find an expert','Experiment','Redesign the approach']],
  ['Mastery','How do you know when work is genuinely good enough?',['A defined standard','The outcome','Feedback','My own professional judgement']],
  ['Enterprise','How often do you look beyond your immediate role for opportunities to create value?',['Constantly','Often','Sometimes','I am beginning to do this']],
  ['Enterprise','When you see a promising idea, what is your next move?',['Test it','Build a case','Find collaborators','Understand the market or need']],
  ['Enterprise','What makes an opportunity worth pursuing?',['Impact','Feasibility','Strategic fit','Potential to create lasting value']],
  ['Presence','How comfortable are you being visible when your work deserves attention?',['Very comfortable','Comfortable with preparation','I prefer my work to speak first','I am becoming more comfortable']],
  ['Relationships','How do you handle conflict when the relationship matters?',['Address it directly','Seek understanding first','Focus on the shared goal','Give the situation time']],
  ['Intelligence','When solving a complex problem, what do you do before acting?',['Define the problem','Identify constraints','Map the system','Clarify what success looks like']],
  ['Mastery','How do you respond when a project does not go as planned?',['Diagnose and adjust','Take ownership','Ask for feedback','Reset the plan']],
  ['Enterprise','What kind of professional growth feels most meaningful?',['Deeper expertise','Greater responsibility','Broader influence','Building something of my own']],
]

const journey = ['Discover','Assess','Build','Connect','Understand']
const letters = { Presence:'P', Relationships:'R', Intelligence:'I', Mastery:'M', Enterprise:'E' }

export default function TestAssessmentPage() {
  const [screen,setScreen] = useState('welcome')
  const [ti,setTi] = useState(0)
  const [fi,setFi] = useState(0); const [fa,setFa] = useState([])
  const [name,setName] = useState(''); const [headline,setHeadline] = useState(''); const [caps,setCaps] = useState([])
  const [profile,setProfile] = useState({photo:false,bio:false,location:false,linkedin:false})
  const [evidence,setEvidence] = useState({Talent:false,Speaker:false,Facilitator:false})
  const [discoverable,setDiscoverable] = useState(false)
    const fullScore = useMemo(() => { const sums={Presence:0,Relationships:0,Intelligence:0,Mastery:0,Enterprise:0}; fa.forEach((v,i)=>{if(v!==undefined)sums[full[i][0]] += Number(v)+1}); const total=Math.round((Object.values(sums).reduce((a,b)=>a+b,0)/(full.length*4))*100); return {sums,total:Math.max(1,Math.min(100,total))} },[fa])
  const stage = screen==='welcome'||screen==='teaser'||screen==='snapshot'?0:screen==='account'||screen==='full'||screen==='full-result'?1:screen==='profile'||screen==='capabilities'?2:screen==='evidence'||screen==='marketplace'||screen==='preview'?3:4
  const progress = screen==='welcome'?0:screen==='teaser'?Math.round(((ti+1)/teaser.length)*24):screen==='snapshot'?25:screen==='account'?30:screen==='full'?24+Math.round(((fi+1)/full.length)*36):screen==='full-result'?60:screen==='profile'?70:screen==='capabilities'?78:screen==='evidence'?86:screen==='marketplace'?92:screen==='preview'?97:100
  const progressLabel = `${progress}% of my Valoria Journey`
  const heroScreen = ['welcome','snapshot','account','full-result','profile','capabilities','evidence','marketplace','preview','report'].includes(screen)
  const reset=()=>{setScreen('welcome');setTi(0);setFi(0);setFa([]);setName('');setHeadline('');setCaps([]);setProfile({photo:false,bio:false,location:false,linkedin:false});setEvidence({Talent:false,Speaker:false,Facilitator:false});setDiscoverable(false)}
  const answerTeaser=()=>{if(ti===teaser.length-1)setScreen('snapshot');else setTi(ti+1)}
  const answerFull=(v)=>{const a=[...fa];a[fi]=v;setFa(a);if(fi===full.length-1)setScreen('full-result');else setFi(fi+1)}
  const goBack=()=>{if(screen==='teaser'&&ti>0)setTi(ti-1);else if(screen==='full'&&fi>0)setFi(fi-1)}
  return <main style={{minHeight:'100vh',height:'100vh',overflow:'hidden',background:'var(--valoria-midnight)',color:'var(--valoria-ivory)',fontFamily:'var(--font,Arial,sans-serif)'}}>
    <header style={{height:76,boxSizing:'border-box',borderBottom:'1px solid rgba(212,201,168,.22)',display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 clamp(18px,5vw,64px)',position:'sticky',top:0,zIndex:10,background:'var(--valoria-midnight)'}}><a href='/' aria-label='Valoria Institute home' style={{display:'flex',alignItems:'center'}}><img src='/logo.png' alt='Valoria Institute' style={{height:42,width:190,objectFit:'contain',objectPosition:'left center'}}/></a><span style={{fontSize:11,color:'rgba(247,244,238,.55)'}}>Prototype · Nothing is stored</span></header>
    <div style={{height:3,background:'rgba(212,201,168,.14)'}}><i style={{display:'block',height:'100%',width:progress+'%',background:'var(--valoria-gold)',transition:'width .35s'}} /></div>
    <div style={{width:'min(1120px,calc(100% - 32px))',height:'calc(100vh - 79px)',boxSizing:'border-box',margin:'0 auto',padding:'10px 0 14px',display:'flex',flexDirection:'column'}}><JourneyProgress progress={progress} label={progressLabel}/>
      <nav style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:7,marginBottom:12,flex:'0 0 auto'}}>{journey.map((x,i)=><div key={x} style={{borderTop:'2px solid '+(i<=stage?'var(--valoria-gold)':'rgba(212,201,168,.18)'),padding:'7px 4px',fontSize:9,letterSpacing:'.09em',fontWeight:i<=stage?800:500,color:i<=stage?'var(--valoria-ivory)':'rgba(247,244,238,.38)',textTransform:'uppercase'}}>{x}</div>)}</nav>
      <section style={{flex:heroScreen?'1 1 auto':'0 0 auto',minHeight:heroScreen?0:'auto',background:'rgba(46,46,74,.72)',border:'1px solid rgba(212,201,168,.28)',borderRadius:8,overflow:'hidden',boxShadow:'none'}}><div style={{height:heroScreen?'100%':'auto',padding:'clamp(16px,2.5vw,32px)',maxWidth:'980px',margin:'0 auto',boxSizing:'border-box',display:'flex',flexDirection:'column',justifyContent:heroScreen?'center':'flex-start',overflowY:heroScreen?'auto':'visible'}}>
        {screen==='welcome' && <><Kicker>THE VALU JOURNEY</Kicker><Title>Understand <em>what makes you valuable.</em></Title><Lead>Begin with your professional snapshot. Then go deeper, build your profile, define the capabilities you want to be known for, and see how your journey comes together in your VALU report.</Lead><Cards items={[['Discover','Start with 15 thoughtful questions across PRIME and see what your professional pattern reveals.'],['Assess','Go deeper through the full VALU assessment and build your official professional picture.'],['Connect','Complete what is missing, define your capabilities and prepare to be discovered.']]}/><Actions><Button onClick={()=>setScreen('teaser')}>START MY JOURNEY →</Button></Actions><Note>This prototype does not create an account, send email or store your responses.</Note></>}
        {screen==='teaser' && <><Kicker>DISCOVER · {teaser[ti][0]}</Kicker><Counter>Question {ti+1} of {teaser.length}</Counter><Question text={teaser[ti][1]}/>{teaser[ti][2].map((x,i)=><Option key={x} onClick={()=>answerTeaser(i)}>{x}</Option>)}<FooterActions back={ti>0} onBack={goBack} onBeginning={reset}/><Note>Take your time. Read each question carefully, then choose the answer that best reflects you today.</Note></>}
        {screen==='snapshot' && <><Kicker>YOUR PROFESSIONAL SNAPSHOT</Kicker><Title>See <em>what your snapshot reveals.</em></Title><Cards items={[['72 / 100','Use this snapshot as your starting point, not as a final judgement.'],['Intelligence','See how your responses currently position you across this dimension.'],['Mastery','Use the full assessment to understand how consistently you apply this capability.']]}/><Callout><b>This is your starting point, not your final picture.</b><p>Use this insight to decide whether you want to go deeper. The full VALU assessment builds your official professional picture.</p></Callout><Actions><Button onClick={()=>setScreen('account')}>CONTINUE MY JOURNEY →</Button></Actions></>}
        {screen==='account' && <><Kicker>YOUR ACCOUNT · SIMULATED</Kicker><Title>Keep going <em>without starting again.</em></Title><Lead>Your snapshot carries forward into the next stage. In this prototype, that handoff is simulated.</Lead><label style={{display:'block',fontSize:12,fontWeight:800,marginTop:28}}>Your name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder='Your name' style={{width:'100%',marginTop:8,padding:15,border:'1px solid rgba(212,201,168,.28)',borderRadius:6,fontSize:16}}/><Actions><Button disabled={!name.trim()} onClick={()=>setScreen('full')}>START MY FULL ASSESSMENT →</Button></Actions><Note>This prototype does not create an account or send anything.</Note></>}
        {screen==='full' && <><Kicker>{full[fi][0]} · FULL VALU ASSESSMENT</Kicker><Counter>Question {fi+1} of {full.length}</Counter><Question text={full[fi][1]}/>{full[fi][2].map((x,i)=><Option key={x} onClick={()=>answerFull(i)}>{x}</Option>)}<FooterActions back={fi>0} onBack={goBack} onBeginning={reset}/><Note>There is no “best” answer. Choose what is most true of you today.</Note></>}
        {screen==='full-result' && <><Kicker>ASSESSMENT COMPLETE</Kicker><Title>Your professional picture is <em>coming into focus.</em></Title><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginTop:18}}><Card title={fullScore.total+'/100'} text='Your VALU Index · Prototype'/>{Object.entries(fullScore.sums).map(([k,v])=><Card key={k} title={letters[k]+' · '+k} text={v+' points captured across this dimension.'}/>)}</div><Callout><b>Your assessment gives you a structured view of where you are today.</b><p>Use it to understand your current position and decide what you want to build next.</p></Callout><Actions><Button onClick={()=>setScreen('profile')}>BUILD MY PROFILE →</Button></Actions></>}
        {screen==='profile' && <><Kicker>BUILD · PROFESSIONAL PROFILE</Kicker><Title>Start with what Valoria <em>already knows.</em></Title><Lead>Your assessment already gives Valoria the foundation. Complete only the information that is still missing — including the language that tells people what you want to be known for.</Lead><div style={{display:'grid',gap:9,marginTop:24}}>{[['Assessment information',true,'Captured from your assessment'],['Professional identity',true,name],['Professional headline',!!headline,headline||'State the value you want to be known for'],['Profile photo',profile.photo,'Add the person behind the professional profile'],['Professional bio',profile.bio,'Tell people what you want to be known for'],['Location',profile.location,'Help relevant opportunities find you'],['LinkedIn',profile.linkedin,'Connect your professional presence']].map(([t,done,d])=><div key={t} style={{display:'flex',gap:12,alignItems:'center',padding:14,border:'1px solid '+(done?'var(--valoria-gold)':'rgba(212,201,168,.28)'),borderRadius:7,background:done?'rgba(46,46,74,.9)':'rgba(26,26,46,.82)'}}><span>{done?'✓':'○'}</span><div style={{flex:1}}><b>{t}</b><div style={{fontSize:12,color:'rgba(247,244,238,.48)',marginTop:3}}>{d}</div>{t==='Professional headline'&&!done&&<input value={headline} onChange={e=>setHeadline(e.target.value)} placeholder='e.g. Strategy and growth professional' style={{width:'100%',marginTop:9,padding:10,boxSizing:'border-box',border:'1px solid rgba(212,201,168,.28)',borderRadius:5}}/>}</div>{!done&&t!=='Professional headline'&&<button onClick={()=>setProfile(p=>({...p,[t==='Profile photo'?'photo':t==='Professional bio'?'bio':t==='Location'?'location':'linkedin']:true}))} style={{border:'1px solid var(--valoria-gold)',background:'rgba(26,26,46,.82)',borderRadius:4,padding:'7px 10px',fontSize:10,fontWeight:800}}>ADD</button>}</div>)}</div><Actions><Button disabled={!headline.trim()} onClick={()=>setScreen('capabilities')}>CONTINUE TO MY CAPABILITIES →</Button></Actions></>}
        {screen==='capabilities' && <><Kicker>BUILD · CAPABILITIES</Kicker><Title>Choose how you want to <em>be discovered.</em></Title><Lead>Keep one professional profile and select the capabilities you want Valoria to surface. You can choose more than one.</Lead><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10,marginTop:24}}>{[['Talent','Professional capability'],['Speaker','Ideas, insight and perspective'],['Facilitator','Meaningful learning experiences']].map(([t,d])=><button key={t} onClick={()=>setCaps(c=>c.includes(t)?c.filter(x=>x!==t):[...c,t])} style={{padding:20,textAlign:'left',border:'1px solid '+(caps.includes(t)?'var(--valoria-gold)':'rgba(212,201,168,.28)'),background:caps.includes(t)?'rgba(201,168,76,.10)':'rgba(26,26,46,.82)',borderRadius:8,cursor:'pointer'}}><b>{t}</b><span style={{display:'block',fontSize:12,color:'rgba(247,244,238,.48)',marginTop:7}}>{d}</span></button>)}</div><Actions><Button disabled={!caps.length} onClick={()=>setScreen('evidence')}>DEFINE MY EVIDENCE →</Button></Actions><Note>This prototype simulates governance and eligibility. No real marketplace listing is changed.</Note></>}
        {screen==='evidence' && <><Kicker>CONNECT · EVIDENCE</Kicker><Title>Make your capability <em>provable.</em></Title><Lead>A capability becomes marketplace-ready when people can see the evidence behind it. Add at least one proof point for each capability you selected.</Lead><div style={{display:'grid',gap:10,marginTop:24}}>{caps.map(c=><div key={c} style={{padding:17,border:'1px solid '+(evidence[c]?'var(--valoria-gold)':'rgba(212,201,168,.28)'),borderRadius:8,background:'rgba(26,26,46,.82)'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><b>{c}</b><span style={{fontSize:10,fontWeight:900,color:evidence[c]?'var(--valoria-gold)':'rgba(247,244,238,.45)',textTransform:'uppercase'}}>{evidence[c]?'Evidence added':'Needs evidence'}</span></div><p style={{fontSize:12,color:'rgba(247,244,238,.5)',lineHeight:1.5}}>Experience, credential, project, outcome, portfolio item or other credible proof of this capability.</p><button onClick={()=>setEvidence(e=>({...e,[c]:!e[c]}))} style={{border:'1px solid var(--valoria-gold)',background:'transparent',color:'var(--valoria-gold)',padding:'9px 13px',borderRadius:9999,fontSize:10,fontWeight:800}}>{evidence[c]?'REMOVE PROOF':'ADD PROOF'}</button></div>)}</div><Actions><Button disabled={!caps.length||!caps.every(c=>evidence[c])} onClick={()=>setScreen('marketplace')}>CHECK MY READINESS →</Button></Actions><Note>In the live platform, evidence can be reviewed and verified before marketplace eligibility is granted.</Note></>}
        {screen==='marketplace' && <><Kicker>CONNECT · ELIGIBILITY</Kicker><Title>Know what makes you <em>ready to be discovered.</em></Title><Lead>Valoria checks your assessment, profile, selected capability and evidence before a listing becomes discoverable. This demo shows the governance step before publication.</Lead><div style={{display:'grid',gap:9,marginTop:22}}>{caps.map(c=><div key={c} style={{display:'flex',alignItems:'center',gap:12,padding:15,border:'1px solid var(--valoria-gold)',borderRadius:7,background:'rgba(46,46,74,.9)'}}><span style={{fontSize:18}}>✓</span><div style={{flex:1}}><b>{c}</b><div style={{fontSize:12,color:'rgba(247,244,238,.5)',marginTop:3}}>Assessment · Profile · Evidence complete</div></div><strong style={{fontSize:10,color:'var(--valoria-gold)',letterSpacing:'.08em'}}>ELIGIBLE</strong></div>)}</div><Callout><b>Eligibility is not the same as listing.</b><p>Your capability can be eligible while the final marketplace listing still requires a clear profile preview and your discoverability action.</p></Callout><Actions><Button gold onClick={()=>setScreen('preview')}>PREVIEW MY LISTING →</Button></Actions></>}
        {screen==='preview' && <><Kicker>CONNECT · GET DISCOVERED</Kicker><Title>See exactly how people will <em>find you.</em></Title><Lead>Review the professional identity Valoria is ready to surface. Your capabilities remain attached to one verified professional profile.</Lead><div style={{marginTop:22,padding:22,border:'1px solid var(--valoria-gold)',borderRadius:8,background:'rgba(26,26,46,.88)'}}><div style={{fontSize:10,color:'var(--valoria-gold)',fontWeight:900,letterSpacing:'.12em'}}>VALORIA MARKETPLACE PREVIEW</div><h2 style={{margin:'12px 0 4px',fontSize:25}}>{name||'Your name'}</h2><div style={{color:'rgba(247,244,238,.68)',fontSize:14}}>{headline||'Your professional headline'}</div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:15}}>{caps.map(c=><span key={c} style={{border:'1px solid rgba(212,201,168,.35)',padding:'6px 9px',borderRadius:9999,fontSize:10}}>{c}</span>)}</div><div style={{marginTop:17,fontSize:12,color:'rgba(247,244,238,.52)'}}>VALU {fullScore.total}/100 · Assessed · Eligible</div></div><Actions><Button gold onClick={()=>setDiscoverable(true)}>{discoverable?'YOU ARE DISCOVERABLE ✓':'MAKE ME DISCOVERABLE →'}</Button></Actions>{discoverable&&<Callout><b>Your profile is now marked discoverable in this demo.</b><p>The live platform would publish the eligible capability listings while keeping one professional identity at the centre.</p></Callout>}<Actions><Button disabled={!discoverable} onClick={()=>setScreen('report')}>CONTINUE TO MY VALU REPORT →</Button></Actions></>}
        {screen==='report' && <><Kicker>UNDERSTAND · VALU REPORT</Kicker><Title>Now you can see <em>the bigger picture.</em></Title><Cards items={[[fullScore.total+'/100','Your VALU Index · Prototype'],[name || 'Professional',caps.join(' · ')],['Development signal','Turn your capability into clearer evidence, stronger positioning and meaningful opportunity.']]}/><Callout><b>Your professional pattern</b><p>Your PRIME pattern shows how you currently approach professional value. The next step is to turn capability into visible, repeatable value.</p></Callout><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:10,marginTop:18}}><Card title='Strengths' text='Identify the patterns that consistently create value in your work.'/><Card title='Growth opportunities' text='Strengthen consistency, visibility and the evidence behind your outcomes.'/><Card title='Next possibilities' text={caps.length?caps.join(', '):'Your selected professional pathways'}/></div><Actions><Button onClick={reset}>START THE JOURNEY AGAIN</Button></Actions><Note>Your prototype journey is complete. Nothing has been stored.</Note></>}
      </div></section>
    </div>
  </main>
}

function Kicker({children}){return <div style={{fontSize:10,fontWeight:900,letterSpacing:'.18em',color:'var(--valoria-gold)',textTransform:'uppercase',marginBottom:14}}>{children}</div>}
function Title({children}){return <h1 style={{fontSize:'clamp(32px,4.8vw,54px)',lineHeight:1.02,letterSpacing:'-.045em',fontWeight:800,margin:'0 0 14px',maxWidth:'820px'}}>{children}</h1>}
function Lead({children}){return <p style={{fontSize:'clamp(14px,1.6vw,16px)',lineHeight:1.7,color:'rgba(247,244,238,.68)',maxWidth:720,margin:'0'}}>{children}</p>}
function Question({text}){return <h2 style={{fontSize:'clamp(24px,4vw,31px)',lineHeight:1.25,letterSpacing:'-.025em',margin:'16px 0 24px'}}>{text}</h2>}
function Counter({children}){return <div style={{fontSize:11,color:'rgba(247,244,238,.48)',marginBottom:8}}>{children}</div>}
function Option({children,onClick}){return <button onClick={onClick} style={{display:'block',width:'100%',textAlign:'left',padding:'17px 18px',background:'rgba(26,26,46,.82)',border:'1px solid rgba(212,201,168,.28)',borderRadius:7,margin:'9px 0',fontSize:15,color:'var(--valoria-ivory)',cursor:'pointer'}}>{children}</button>}
function Button({children,onClick,disabled,gold}){return <button disabled={disabled} onClick={onClick} style={{minHeight:48,border:0,borderRadius:'9999px',padding:'0 24px',fontSize:11,fontWeight:900,letterSpacing:'.08em',cursor:disabled?'not-allowed':'pointer',background:gold?'var(--valoria-gold)':'var(--valoria-gold)',color:'var(--valoria-midnight)',opacity:disabled?.4:1}}>{children}</button>}
function Actions({children}){return <div style={{display:'flex',gap:9,flexWrap:'wrap',marginTop:28}}>{children}</div>}
function FooterActions({back,onBack,onBeginning}){return <div style={{marginTop:24,display:'flex',gap:9,flexWrap:'wrap'}}>{back&&<button onClick={onBack} style={{border:'1px solid var(--valoria-gold)',background:'transparent',color:'var(--valoria-gold)',padding:'11px 18px',borderRadius:'9999px',cursor:'pointer',fontSize:11,fontWeight:800}}>← BACK</button>}<button onClick={onBeginning} style={{border:'1px solid rgba(212,201,168,.35)',background:'transparent',color:'rgba(247,244,238,.65)',padding:'11px 18px',borderRadius:'9999px',cursor:'pointer',fontSize:11,fontWeight:800}}>↑ BEGINNING</button></div>}
function Note({children}){return <p style={{fontSize:12,color:'rgba(247,244,238,.48)',lineHeight:1.6,marginTop:18}}>{children}</p>}
function Card({title,text}){return <div style={{background:'rgba(26,26,46,.82)',border:'1px solid rgba(212,201,168,.28)',borderRadius:8,padding:'14px 16px',minHeight:72,boxSizing:'border-box'}}><b style={{display:'block',fontSize:16}}>{title}</b><span style={{display:'block',fontSize:12,lineHeight:1.6,color:'rgba(247,244,238,.55)',marginTop:7}}>{text}</span></div>}
function JourneyProgress({progress,label}){return <div style={{marginBottom:22,padding:'14px 16px',border:'1px solid rgba(212,201,168,.18)',borderRadius:8,background:'rgba(26,26,46,.5)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:9}}><span style={{fontSize:10,fontWeight:800,letterSpacing:'.12em',color:'var(--valoria-gold)',textTransform:'uppercase'}}>MY JOURNEY PROGRESS</span><strong style={{fontSize:12,color:'var(--valoria-ivory)'}}>{label}</strong></div><div style={{height:5,borderRadius:9999,background:'rgba(212,201,168,.14)',overflow:'hidden'}}><div style={{height:'100%',width:progress+'%',background:'var(--valoria-gold)',borderRadius:9999,transition:'width .35s ease'}}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:4,marginTop:8}}>{journey.map((x,i)=><span key={x} style={{fontSize:8,color:i<=Math.floor(progress/20)?'rgba(247,244,238,.72)':'rgba(247,244,238,.3)',letterSpacing:'.06em',textTransform:'uppercase'}}>{x}</span>)}</div></div>}
function Cards({items}){return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginTop:20}}>{items.map(([t,d])=><Card key={t} title={t} text={d}/>)}</div>}
function Callout({children}){return <div style={{borderLeft:'3px solid var(--valoria-gold)',paddingLeft:17,marginTop:25,color:'var(--valoria-ivory)'}}>{children}</div>}
