'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {supabase} from '@/lib/supabase'
const G='#C9A84C',D='#0F0F1A',P='#F7F4EE',M='#1A1A2E'
export default function OpportunityReview(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[error,setError]=useState('')
 async function load(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/admin/login';return}const r=await fetch('/api/admin/opportunities',{headers:{Authorization:'Bearer '+session.access_token}});const j=await r.json();if(!r.ok)setError(j.error||'Could not load submissions');else setRows(j.submissions||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 async function review(id,status){setBusy(id);setError('');const {data:{session}}=await supabase.auth.getSession();const r=await fetch('/api/admin/opportunities',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({submissionId:id,status,adminNotes:status==='approved'?'Approved for Valoria publication.':''})});const j=await r.json();if(!r.ok)setError(j.error||'Review failed');else setRows(xs=>xs.map(x=>x.id===id?{...x,status}:x));setBusy(null)}
 if(loading)return <main style={s.root}>Loading opportunity review…</main>
 return <main style={s.root}><header style={s.header}><Link href="/admin" style={s.link}>← Administration</Link><div style={{display:'flex',gap:18,alignItems:'center'}}><Link href="/admin/opportunities/invite" style={s.link}>INVITE PROFESSIONAL</Link><b>OPPORTUNITY REVIEW</b></div></header><section style={s.wrap}><h1 style={s.h1}>Opportunity submissions</h1><p style={s.dim}>External submissions remain unpublished until an administrator approves them.</p>{error&&<p style={s.error}>{error}</p>}<div style={s.list}>{rows.map(x=><article style={s.row} key={x.id}><div><b>{x.opportunity?.title||'Opportunity submission'}</b><div style={s.dim}>{x.organisation_name||x.opportunity?.organisation_name||'Organisation not specified'} · {x.submitter_name} · {x.submitter_email}</div><p style={s.body}>{x.opportunity?.description||x.opportunity?.summary||'No description supplied.'}</p><div style={s.tags}><span>{x.opportunity?.opportunity_type||'job'}</span><span>{x.status}</span>{x.opportunity?.work_mode&&<span>{x.opportunity.work_mode}</span>}</div></div>{x.status!=='approved'&&x.status!=='rejected'&&<div style={s.actions}><button disabled={busy===x.id} onClick={()=>review(x.id,'approved')} style={s.btn}>APPROVE & PUBLISH</button><button disabled={busy===x.id} onClick={()=>review(x.id,'changes_requested')} style={s.outline}>CHANGES</button><button disabled={busy===x.id} onClick={()=>review(x.id,'rejected')} style={s.danger}>REJECT</button></div>}</article>)}</div>{!rows.length&&<div style={s.empty}>No submissions yet.</div>}</section></main>
}
const s={root:{minHeight:'100vh',background:D,color:P,fontFamily:'Raleway,Arial'},header:{height:64,padding:'0 28px',display:'flex',justifyContent:'space-between',alignItems:'center',background:M,borderBottom:'1px solid rgba(201,168,76,.15)',fontSize:11,letterSpacing:'.12em'},link:{color:G,textDecoration:'none'},wrap:{maxWidth:1180,margin:'0 auto',padding:'42px 24px 80px'},h1:{fontSize:40,fontWeight:500,margin:'0 0 8px'},dim:{color:'rgba(247,244,238,.55)',fontSize:12,lineHeight:1.7},list:{display:'grid',gap:12,marginTop:28},row:{background:M,border:'1px solid rgba(201,168,76,.1)',padding:20,borderRadius:8,display:'flex',justifyContent:'space-between',gap:24,alignItems:'center'},body:{fontSize:13,lineHeight:1.6,color:'rgba(247,244,238,.72)'},tags:{display:'flex',gap:10,fontSize:9,textTransform:'uppercase',letterSpacing:'.08em',color:G},actions:{display:'flex',gap:7,flexWrap:'wrap'},btn:{border:0,background:G,color:D,padding:'9px 11px',fontWeight:700,fontSize:10},outline:{background:'transparent',color:G,border:'1px solid rgba(201,168,76,.4)',padding:'8px 10px',fontSize:10},danger:{background:'transparent',color:'#D85A30',border:'1px solid rgba(216,90,48,.4)',padding:'8px 10px',fontSize:10},empty:{padding:40,textAlign:'center',color:'rgba(247,244,238,.55)'},error:{color:'#F0A48E'}}
