'use client'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'

const GOLD='#C9A84C', DARK='#0F0F1A', PARCH='#F7F4EE'
export default function ValuCompletionNudge(){
  const [show,setShow]=useState(false)
  useEffect(()=>{let active=true;async function load(){try{if(sessionStorage.getItem('valu_nudge_dismissed_today')===new Date().toISOString().slice(0,10))return}catch{}const {data:{user}}=await supabase.auth.getUser();if(!user||!active)return;const {data:profile}=await supabase.from('professional_profiles').select('profile_complete').eq('id',user.id).maybeSingle();if(!profile||profile.profile_complete)return;if(active)setShow(true)}load();return()=>{active=false}},[])
  if(!show)return null
  function dismiss(){try{sessionStorage.setItem('valu_nudge_dismissed_today',new Date().toISOString().slice(0,10))}catch{}setShow(false)}
  return <div style={S.overlay} role="dialog" aria-modal="true" aria-label="Complete your professional profile"><div style={S.card}><button onClick={dismiss} aria-label="Close" style={S.close}>×</button><div style={S.eyebrow}>YOUR PROFESSIONAL PROFILE</div><h2 style={S.title}>Your VALU Index is your starting signal. Your profile makes it useful.</h2><p style={S.copy}>Complete your professional profile so Valoria can make your capability discoverable. Your deeper VALU assessment remains available later for advanced opportunities.</p><a href="/profile/setup" style={S.button}>COMPLETE MY PROFILE →</a><button onClick={dismiss} style={S.later}>Remind me later</button></div></div>
}
const S={overlay:{position:'fixed',inset:0,zIndex:2000,display:'flex',alignItems:'flex-end',justifyContent:'center',padding:'20px',background:'rgba(15,15,26,.28)',pointerEvents:'none'},card:{position:'relative',width:'100%',maxWidth:520,padding:'24px 24px 20px',background:'#1A1A2E',border:'1px solid rgba(201,168,76,.3)',borderRadius:12,boxShadow:'0 20px 60px rgba(0,0,0,.35)',pointerEvents:'auto'},close:{position:'absolute',top:8,right:10,border:0,background:'none',color:'rgba(247,244,238,.4)',fontSize:22,cursor:'pointer'},eyebrow:{fontSize:9,fontWeight:700,letterSpacing:'.16em',color:GOLD},title:{fontSize:24,fontWeight:300,color:PARCH,margin:'8px 0'},copy:{fontSize:13,lineHeight:1.65,color:'rgba(247,244,238,.55)',margin:'0 0 18px'},button:{display:'block',padding:'13px 18px',background:GOLD,color:DARK,borderRadius:999,textDecoration:'none',textAlign:'center',fontSize:10,fontWeight:700,letterSpacing:'.12em'},later:{display:'block',width:'100%',marginTop:9,padding:8,border:0,background:'transparent',color:'rgba(247,244,238,.35)',cursor:'pointer',fontSize:11}}
