'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
const G='#C9A84C',D='#0F0F1A',M='#1A1A2E',P='#F7F4EE'
export default function EmployerDashboard(){
 const [apps,setApps]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('')
 async function load(){try{const r=await fetch('/api/employer/applications');const j=await r.json();if(!r.ok){if(r.status===401){location.href='/login?returnTo=/employer/dashboard';return}throw new Error(j.error||'Applications could not be loaded.')}setApps(j.applications||[])}catch(e){setError(e.message||'Applications could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 async function update(id,status){setBusy(id);setError('');try{const r=await fetch('/api/employer/applications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Status could not be updated.');setApps(xs=>xs.map(a=>a.id===id?{...a,status:j.application.status}:a))}catch(e){setError(e.message||'Status could not be updated.')}finally{setBusy('')}}
 return <main style={{minHeight:'100vh',background:D,color:P,fontFamily:'Raleway,sans-serif'}}><header style={{height:70,padding:'0 6vw',display:'flex',justifyContent:'space-between',alignItems:'center',background:M,borderBottom:'1px solid rgba(201,168,76,.15)'}}><Link href="/opportunities" style={{color:G,textDecoration:'none'}}>← Opportunities</Link><b style={{fontSize:11,letterSpacing:'.14em'}}>EMPLOYER DASHBOARD</b></header><section style={{maxWidth:1100,margin:'auto',padding:'55px 6vw 100px'}}><div style={{fontSize:10,color:G,letterSpacing:'.16em',fontWeight:800}}>CAPABILITY ACQUISITION</div><h1 style={{fontSize:'clamp(38px,6vw,64px)',margin:'10px 0 8px'}}>Review your applicants.</h1><p style={{opacity:.65,lineHeight:1.7,maxWidth:700}}>Review assessed professionals, move applications through your hiring process and open the conversation when you are ready.</p>{error&&<div style={{margin:'20px 0',padding:16,border:'1px solid rgba(216,90,48,.35)',borderRadius:22}}>{error}</div>}{loading?<p>Loading applications…</p>:apps.length===0?<div style={{marginTop:30,padding:30,border:'1px solid rgba(201,168,76,.15)',borderRadius:22}}>No applications yet. Published opportunities will appear here when professionals apply.</div>:<div style={{display:'grid',gap:14,marginTop:30}}>{apps.map(a=><article key={a.id} style={{padding:22,border:'1px solid rgba(201,168,76,.18)',borderRadius:22,background:M}}><div style={{display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'}}><div><div style={{fontSize:10,color:G,letterSpacing:'.12em'}}>{a.opportunities?.title||'Opportunity'}</div><h2 style={{margin:'7px 0'}}>{a.professional_profiles?.display_name||'Professional'}</h2><p style={{margin:0,opacity:.65}}>{a.professional_profiles?.headline||a.professional_profiles?.current_job_title||'Professional profile'} · VALU {a.professional_profiles?.valu_index??'—'}</p></div><strong style={{color:G,textTransform:'uppercase',fontSize:10,letterSpacing:'.1em'}}>{a.status}</strong></div>{a.cover_note&&<p style={{lineHeight:1.7,opacity:.78,margin:'18px 0 0'}}>{a.cover_note}</p>}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:18}}>{['reviewing','shortlisted','introduced','interview','selected','declined'].map(s=><button key={s} disabled={busy===a.id} onClick={()=>update(a.id,s)} style={{padding:'9px 12px',border:'1px solid rgba(201,168,76,.22)',borderRadius:22,background:'transparent',color:P,fontFamily:'Raleway,sans-serif',fontSize:10,cursor:'pointer'}}>{s.toUpperCase()}</button>)}<Link href={'/profile/applications/'+a.id} style={{padding:'9px 12px',color:G,fontSize:10,fontWeight:800,textDecoration:'none'}}>OPEN CONVERSATION →</Link></div></article>)}</div>}</section></main>
}
