'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {supabase} from '@/lib/supabase'
const G='#C9A84C',D='#0F0F1A',P='#F7F4EE',M='#1A1A2E'
export default function Reconciliation(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/admin/login';return}const r=await fetch('/api/admin/reconciliation',{headers:{Authorization:'Bearer '+session.access_token}});const j=await r.json();if(!r.ok)setError(j.error||'Could not load reconciliation');else setData(j);setLoading(false)})()},[])
 if(loading)return <main style={s.root}>Loading reconciliation…</main>
 return <main style={s.root}><header style={s.header}><Link href="/admin" style={s.link}>← Administration</Link><b>PLATFORM RECONCILIATION</b></header><section style={s.wrap}><h1 style={s.h1}>Professional journey</h1><p style={s.dim}>One operational view from assessment through eligibility and marketplace listing.</p>{error&&<p style={s.error}>{error}</p>}<div style={s.grid}>{Object.entries(data?.counts||{}).map(([k,v])=><div style={s.card} key={k}><small>{k.replaceAll('_',' ')}</small><strong>{v}</strong></div>)}<div style={s.card}><small>unlinked assessments</small><strong>{data?.orphanedAssessments?.length||0}</strong></div></div><div style={s.list}>{(data?.rows||[]).map(r=><article style={s.row} key={r.user_id}><div><b>{r.display_name}</b><div style={s.dim}>{r.current_job_title} · {r.email||'No assessment email'}</div><div style={s.tags}><span>{r.lifecycle_state.replaceAll('_',' ')}</span>{r.assessment_score!=null&&<span>VALU {r.assessment_score}/100</span>}{r.profile_complete&&<span>PROFILE READY</span>}{(r.capabilities||[]).map(c=><span key={c.capability}>{c.capability}: {c.eligibility_status}</span>)}</div></div><Link href={'/profile/'+r.user_id} style={s.btn}>OPEN</Link></article>)}</div><h2 style={s.h2}>Assessments awaiting account claim</h2>{(data?.orphanedAssessments||[]).map(a=><div style={s.row} key={a.id}><div><b>{a.name||'Unnamed'}</b><div style={s.dim}>{a.email||'No email'} · {a.role||'—'} · VALU {a.total_score??'—'}</div></div><Link href="/profile/claim-assessment" style={s.btn}>CLAIM FLOW</Link></div>)}</section></main>
}
const s={root:{minHeight:'100vh',background:D,color:P,fontFamily:'Raleway,Arial'},header:{height:64,padding:'0 28px',display:'flex',justifyContent:'space-between',alignItems:'center',background:M,borderBottom:'1px solid rgba(201,168,76,.15)',fontSize:11,letterSpacing:'.12em'},link:{color:G,textDecoration:'none'},wrap:{maxWidth:1180,margin:'0 auto',padding:'42px 24px 80px'},h1:{fontSize:40,fontWeight:500,margin:'0 0 8px'},h2:{fontSize:20,fontWeight:500,margin:'34px 0 14px'},dim:{color:'rgba(247,244,238,.55)',fontSize:12,lineHeight:1.7},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,margin:'28px 0'},card:{background:M,border:'1px solid rgba(201,168,76,.12)',padding:16,borderRadius:8},small:{display:'block',fontSize:10,textTransform:'uppercase',color:'rgba(247,244,238,.55)',letterSpacing:'.1em'},list:{display:'grid',gap:10},row:{background:M,border:'1px solid rgba(201,168,76,.1)',padding:17,borderRadius:8,display:'flex',justifyContent:'space-between',gap:18,alignItems:'center'},tags:{display:'flex',gap:6,flexWrap:'wrap',marginTop:10},tag:{fontSize:9},btn:{color:D,background:G,padding:'8px 12px',textDecoration:'none',fontSize:10,fontWeight:700,whiteSpace:'nowrap'},error:{color:'#F0A48E'}}
