'use client'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
const GOLD='#C9A84C',DARK='#1A1A2E',PARCH='#F7F4EE'
export default function ClaimAssessment(){
 const [email,setEmail]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState('')
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setEmail(data?.user?.email||''))},[])
 async function claim(e){e.preventDefault();setBusy(true);setError('');const {data:{session}}=await supabase.auth.getSession();try{const r=await fetch('/api/assessment/claim',{method:'POST',headers:{Authorization:'Bearer '+session?.access_token,'Content-Type':'application/json'},body:JSON.stringify({email})});const x=await r.json();if(!r.ok)throw Error(x.error);setResult(x)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',background:PARCH,color:DARK,padding:'90px 7vw',fontFamily:'Raleway,Arial'}}><div style={{maxWidth:650,margin:'auto'}}><div style={{color:GOLD,fontWeight:800,letterSpacing:'.16em',fontSize:11}}>CONTINUE YOUR VALORIA JOURNEY</div><h1 style={{fontSize:50,lineHeight:1.05}}>Already took VALU?</h1><p style={{lineHeight:1.7,opacity:.68}}>Connect your previous completed assessment to this account. Your original score, answers, PRIME results and report remain historical records; nothing is recalculated or replaced.</p><form onSubmit={claim}><label style={{fontSize:12,fontWeight:800}}>ASSESSMENT EMAIL<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required style={{display:'block',width:'100%',padding:15,marginTop:8,marginBottom:16}}/></label><button disabled={busy} style={{padding:'15px 22px',background:GOLD,border:0,fontWeight:800}}>{busy?'CHECKING…':'FIND MY EXISTING ASSESSMENT'}</button></form>{error&&<p style={{marginTop:20,color:'#9b3030'}}>{error}</p>}{result&&<div style={{marginTop:28,padding:24,border:'1px solid #D4C9A8',background:'#FAFAF7'}}><div style={{fontSize:11,letterSpacing:'.12em',fontWeight:800}}>ASSESSMENT PRESERVED</div><h2 style={{fontSize:34,margin:'10px 0'}}>VALU {result.assessment.total_score ?? '—'}</h2><p>Your previous assessment is now connected to your account. Continue your profile journey from the dashboard.</p><a href="/dashboard" style={{color:DARK,fontWeight:800}}>CONTINUE TO DASHBOARD →</a></div>}</div></main>
}