'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {supabase} from '@/lib/supabase'
const GOLD='#C9A84C',DARK='#1A1A2E',PARCH='#F7F4EE'
export default function ClaimAssessment(){
 const router=useRouter();const [email,setEmail]=useState(''),[tasterId,setTasterId]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState('')
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setEmail(data?.user?.email||'');const id=typeof window!=='undefined'?localStorage.getItem('pending_taster_id'):'';if(id)setTasterId(id)})},[])
 async function claim(e){e?.preventDefault();setBusy(true);setError('');const {data:{session}}=await supabase.auth.getSession();try{const r=await fetch('/api/assessment/claim',{method:'POST',headers:{Authorization:'Bearer '+session?.access_token,'Content-Type':'application/json'},body:JSON.stringify({email,taster_id:tasterId||undefined})});const x=await r.json();if(!r.ok)throw Error(x.error);if(typeof window!=='undefined')localStorage.removeItem('pending_taster_id');setResult(x)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',background:PARCH,color:DARK,padding:'90px 7vw',fontFamily:'Raleway,Arial'}}><div style={{maxWidth:650,margin:'auto'}}><div style={{color:GOLD,fontWeight:800,letterSpacing:'.16em',fontSize:11}}>CONTINUE YOUR VALORIA JOURNEY</div><h1 style={{fontSize:50,lineHeight:1.05}}>Your Valoria journey continues.</h1><p style={{lineHeight:1.7,opacity:.68}}>We preserve what you have already completed. Your previous snapshot, VALU assessment, score, PRIME results and report remain historical records. We connect them to your account and continue from the point you reached.</p>{tasterId?<div style={{padding:18,margin:'22px 0',border:'1px solid #D4C9A8'}}>A previous Valoria snapshot was detected. We will use it to restore your journey.</div>:<form onSubmit={claim}><label style={{fontSize:12,fontWeight:800}}>ACCOUNT EMAIL<input value={email} readOnly type="email" style={{display:'block',width:'100%',padding:15,marginTop:8,marginBottom:16}}/></label></form>}<button disabled={busy} onClick={claim} style={{padding:'15px 22px',background:GOLD,border:0,fontWeight:800}}>{busy?'RESTORING YOUR JOURNEY…':tasterId?'RESTORE MY VALORIA JOURNEY':'FIND MY EXISTING ASSESSMENT'}</button>{error&&<p style={{marginTop:20,color:'#9b3030'}}>{error}</p>}{result&&<div style={{marginTop:28,padding:24,border:'1px solid #D4C9A8',background:'#FAFAF7'}}><div style={{fontSize:11,letterSpacing:'.12em',fontWeight:800}}>JOURNEY RESTORED</div><h2 style={{fontSize:34,margin:'10px 0'}}>VALU {result.assessment.total_score ?? '—'}</h2><p>Your previous work is connected. Nothing was recalculated or discarded. Continue from your canonical Valoria path.</p><button onClick={()=>router.push('/dashboard')} style={{background:'none',border:0,padding:0,color:DARK,fontWeight:800}}>CONTINUE TO DASHBOARD →</button></div>}</div></main>
}